### ISSUE TITLE
NFC data enhancements

### ISSUE THREAD

**Issue by theBASTI0N** [theBASTI0N/ruuvitag_fw_zephyr#7]
Look into if sensor data could be added into NFC data. For example records would be added for each temp, humidity, acc events. This data should be updated periodically, say every 1 minute.

**Comment by ojousima** [comment]
Latest 3.x Ruuvi FW built on top of of Nordic SDK places the data as a RAWv2 binary in UTF-8 text field.

**Comment by theBASTI0N** [comment]
Awesome thanks for that I will have a look at that and see if I can get it working.

**Comment by theBASTI0N** [comment]
RAWv2 data is now included in NFC data and is updated every minute in:

@https://github.com/theBASTI0N/ruuvitag_fw_zephyr/releases/tag/v1.1.0
